optimize

diff --git a/cmakew b/cmakew
--- a/cmakew
+++ b/cmakew
@@ -220,7 +220,7 @@ __fetch_archive_via_tools() {
     AVAILABLE_FETCH_TOOL=$(__get_available_fetch_tool)
 
     if [ -z "$AVAILABLE_FETCH_TOOL" ] ; then
-        __handle_required_item required command curl || return 1
+        handle_dependency required command curl || return 1
         if exists command curl ; then
             AVAILABLE_FETCH_TOOL=curl
         else
@@ -1147,7 +1147,7 @@ __install_command_via_package_manager() {
 # python3    ge 3.5
 # make
 __install_command_via_available_package_manager() {
-    if required_command_exists_and_version_matched $@ ; then
+    if command_exists_and_version_matched $@ ; then
         return 0
     else
         if [ -z "$AVAILABLE_PACKAGE_MANAGER_LIST" ] ; then
@@ -1191,37 +1191,37 @@ __install_command_via_fetch_prebuild_binary() {
 
     case $1 in
         *.zip)
-            __handle_required_item required command unzip &&
+            handle_dependency required command unzip &&
             run unzip "$PREBUILD_BINARY_FILEPATH" -d "$PREBUILD_BINARY_UNPACK_DIR/$2"
             ;;
         *.tar.xz)
-            __handle_required_item required command tar  &&
-            __handle_required_item required command xz   &&
+            handle_dependency required command tar  &&
+            handle_dependency required command xz   &&
             run tar xf "$PREBUILD_BINARY_FILEPATH" -C "$PREBUILD_BINARY_UNPACK_DIR/$2" --strip-components 1
             ;;
         *.tar.gz)
-            __handle_required_item required command tar  &&
-            __handle_required_item required command gzip &&
+            handle_dependency required command tar  &&
+            handle_dependency required command gzip &&
             run tar xf "$PREBUILD_BINARY_FILEPATH" -C "$PREBUILD_BINARY_UNPACK_DIR/$2" --strip-components 1
             ;;
         *.tar.lz)
-            __handle_required_item required command tar  &&
-            __handle_required_item required command lzip &&
+            handle_dependency required command tar  &&
+            handle_dependency required command lzip &&
             run tar xf "$PREBUILD_BINARY_FILEPATH" -C "$PREBUILD_BINARY_UNPACK_DIR/$2" --strip-components 1
             ;;
         *.tar.bz2)
-            __handle_required_item required command tar   &&
-            __handle_required_item required command bzip2 &&
+            handle_dependency required command tar   &&
+            handle_dependency required command bzip2 &&
             run tar xf "$PREBUILD_BINARY_FILEPATH" -C "$PREBUILD_BINARY_UNPACK_DIR/$2" --strip-components 1
             ;;
         *.tgz)
-            __handle_required_item required command tar  &&
-            __handle_required_item required command gzip &&
+            handle_dependency required command tar  &&
+            handle_dependency required command gzip &&
             run tar xf "$PREBUILD_BINARY_FILEPATH" -C "$PREBUILD_BINARY_UNPACK_DIR/$2" --strip-components 1
             ;;
         *.txz)
-            __handle_required_item required command tar &&
-            __handle_required_item required command xz  &&
+            handle_dependency required command tar &&
+            handle_dependency required command xz  &&
             run tar xf "$PREBUILD_BINARY_FILEPATH" -C "$PREBUILD_BINARY_UNPACK_DIR/$2" --strip-components 1
     esac
 
@@ -1263,7 +1263,7 @@ __get_prebuild_binary_fetch_url_by_command_name() {
 # python3    ge 3.5
 # make
 __install_command() {
-    if required_command_exists_and_version_matched $@ ; then
+    if command_exists_and_version_matched $@ ; then
         return 0
     else
         unset PREBUILD_BINARY_FETCH_URL
@@ -1280,7 +1280,7 @@ __install_command() {
 # pkg-config ge 0.18
 # python3    ge 3.5
 # make
-required_command_exists_and_version_matched() {
+command_exists_and_version_matched() {
     if exists command "$1" ; then
         if [ "$NATIVE_OS_TYPE" = 'cygwin' ] ; then
             case $(command -v "$1") in
@@ -1296,12 +1296,20 @@ required_command_exists_and_version_matched() {
 }
 
 # examples:
-# required command pkg-config ge 0.18
-# required command python3    ge 3.5
-# optional python3 libxml2    ge 2.8
-# optional python3 libxml2
-__handle_required_item() {
+# handle_dependency required command pkg-config ge 0.18
+# handle_dependency required command python     ge 3.5
+# handle_dependency required python  libxml2    ge 2.19
+#
+# handle_dependency optional command pkg-config ge 0.18
+# handle_dependency optional command python     ge 3.5
+# handle_dependency optional python  libxml2    ge 2.19
+handle_dependency() {
+    if [ "$1" != 'required' ] ; then
+        return 0
+    fi
+
     shift
+
     case $1 in
         command)
             shift
@@ -1309,7 +1317,7 @@ __handle_required_item() {
                 *:*)
                     for item in $(echo "$1" | tr ':' ' ')
                     do
-                        if required_command_exists_and_version_matched "$item" $2 $3 ; then
+                        if command_exists_and_version_matched "$item" $2 $3 ; then
                             eval "REQUIRED_ITEM_$REQUIRED_ITEM_INDEX=$item"
                             return 0
                         fi
@@ -1351,13 +1359,30 @@ __handle_required_item() {
     esac
 }
 
+__handle_required_dependencies() {
+    [ "$DEBUG" = 'true' ] && step "handle required dependencies"
+
+    for item in $REQUIRED_DEPENDENCY_LIST
+    do
+        REQUIRED_ITEM_INDEX=$(expr ${REQUIRED_ITEM_INDEX-0} + 1)
+        handle_dependency $(__decode_dependency "$item") || return 1
+    done
+    unset REQUIRED_ITEM_INDEX
+}
+
+# }}}
+##############################################################################
+# {{{ __printf_dependencies
+
 # examples:
-#    $1      $2      $3       $4  $5
-# required command pkg-config ge 0.18
-# required command python3    ge 3.5
-# optional python3 libxml2    ge 2.8
-# optional python3 libxml2
-__print_required_or_optional_item() {
+# printf_dependency required command pkg-config ge 0.18
+# printf_dependency required command python     ge 3.5
+# printf_dependency required python  libxml2    ge 2.19
+#
+# printf_dependency optional command pkg-config ge 0.18
+# printf_dependency optional command python     ge 3.5
+# printf_dependency optional python  libxml2    ge 2.19
+printf_dependency() {
     case $2 in
         command)
             case $3 in
@@ -1385,6 +1410,40 @@ __print_required_or_optional_item() {
     esac
 }
 
+__printf_required_dependencies() {
+    step "printf required dependencies"
+    if [ -z "$REQUIRED_DEPENDENCY_LIST" ] ; then
+        warn "no required dependencies."
+    else
+        printf "%-7s %-11s %-10s %-10s %s\n" TYPE NAME EXPECTED ACTUAL LOCATION
+        for item in $REQUIRED_DEPENDENCY_LIST
+        do
+            REQUIRED_ITEM_INDEX=$(expr ${REQUIRED_ITEM_INDEX-0} + 1)
+            printf_dependency $(__decode_dependency "$item")
+        done
+        unset REQUIRED_ITEM_INDEX
+    fi
+}
+
+__printf_optional_dependencies() {
+    step "printf optional dependencies"
+    if [ -z "$OPTIONAL_DEPENDENCY_LIST" ] ; then
+        warn "no optional dependencies."
+    else
+        printf "%-7s %-11s %-10s %-10s %s\n" TYPE NAME EXPECTED ACTUAL LOCATION
+        for item in $OPTIONAL_DEPENDENCY_LIST
+        do
+            OPTIONAL_ITEM_INDEX=$(expr ${OPTIONAL_ITEM_INDEX-0} + 1)
+            printf_dependency $(__decode_dependency "$item")
+        done
+        unset OPTIONAL_ITEM_INDEX
+    fi
+}
+
+# }}}
+##############################################################################
+# {{{ location_of_python_module
+
 location_of_python_module() {
     PIP_COMMAND=$(command -v pip3 || command -v pip)
     if [ -z "$PIP_COMMAND" ] ; then
@@ -1394,7 +1453,11 @@ location_of_python_module() {
     fi
 }
 
-__encode() {
+# }}}
+##############################################################################
+# {{{ encode/decode dependency
+
+__encode_dependency() {
     if [ $# -eq 0 ] ; then
         tr ' ' '|'
     else
@@ -1402,7 +1465,7 @@ __encode() {
     fi
 }
 
-__decode() {
+__decode_dependency() {
     if [ $# -eq 0 ] ; then
         tr '|' ' '
     else
@@ -1410,94 +1473,57 @@ __decode() {
     fi
 }
 
-# declare required command or python/perl module
+# }}}
+##############################################################################
+# {{{ regist dependency
+
+# regist dependency
 #
-# $1 type=command|python|python2|python3|perl
-#    type can be omitted when it is command
-# $2 name
-# $3=gt|lt|ge|le|eq|ne
-# $4 version
+# required this is a required dependency
+# optional this is a optional dependency
+#
+# command  this dependency is a command
+# python   this dependency is a python  module
+# python2  this dependency is a python2 module
+# python3  this dependency is a python3 module
+# perl     this dependency is a perl module
+#
+# gt VERSION
+# ge VERSION
+# lt VERSION
+# le VERSION
+# eq VERSION
+# ne VERSION
 #
 # examples:
-# required command pkg-config ge 0.18
-# required command python     ge 3.5
-# required python  libxml2    ge 2.19
-required() {
-    if [ $# -eq 2 ] || [ $# -eq 4 ] ; then
-        if [ -z "$REQUIRED" ] ; then
-            REQUIRED="$(__encode "required $*")"
-        else
-            REQUIRED="$REQUIRED $(__encode "required $*")"
-        fi
-    else
-        die "required $@ : required function accept 2 or 4 argument."
-    fi
-}
-
-# declare optional command or python/perl module
+# regist_dependency required command pkg-config ge 0.18
+# regist_dependency required command python     ge 3.5
+# regist_dependency required python  libxml2    ge 2.19
 #
-# $1 type=command|python|python2|python3|perl
-#    type can be omitted when it is command
-# $2 name
-# $3=gt|lt|ge|le|eq|ne
-# $4 version
-#
-# examples:
-# optional command pkg-config ge 0.18
-# optional command python     ge 3.5
-# optional python  libxml2    ge 2.19
-optional() {
-    if [ $# -eq 2 ] || [ $# -eq 4 ] ; then
-        if [ -z "$OPTIONAL" ] ; then
-            OPTIONAL=$(__encode "optional $*")
-        else
-            OPTIONAL="$OPTIONAL $(__encode "optional $*")"
-        fi
-    else
-        die "optional $@ : optional function accept 2 or 4 argument."
-    fi
-}
-
-__handle_required_dependencies() {
-    [ "$DEBUG" = 'true' ] &&
-    step "handle required dependencies"
-
-    for item in $REQUIRED
+# regist_dependency optional command pkg-config ge 0.18
+# regist_dependency optional command python     ge 3.5
+# regist_dependency optional python  libxml2    ge 2.19
+regist_dependency() {
+    for item in $@
     do
-        REQUIRED_ITEM_INDEX=$(expr ${REQUIRED_ITEM_INDEX-0} + 1)
-        __handle_required_item $(__decode "$item") || return 1
+        case $item in
+            required)
+                if [ -z "$REQUIRED_DEPENDENCY_LIST" ] ; then
+                    REQUIRED_DEPENDENCY_LIST="$(__encode_dependency "$*")"
+                else
+                    REQUIRED_DEPENDENCY_LIST="$REQUIRED_DEPENDENCY_LIST $(__encode_dependency "$*")"
+                fi
+                break
+                ;;
+            optional)
+                if [ -z "$OPTIONAL_DEPENDENCY_LIST" ] ; then
+                    OPTIONAL_DEPENDENCY_LIST=$(__encode_dependency "$*")
+                else
+                    OPTIONAL_DEPENDENCY_LIST="$OPTIONAL_DEPENDENCY_LIST $(__encode_dependency "$*")"
+                fi
+                break
+        esac
     done
-    unset REQUIRED_ITEM_INDEX
-}
-
-__printf_required_dependencies() {
-    step "list required dependencies"
-    if [ -z "$REQUIRED" ] ; then
-        warn "no required dependencies."
-    else
-        printf "%-7s %-11s %-10s %-10s %s\n" TYPE NAME EXPECTED ACTUAL LOCATION
-        for item in $REQUIRED
-        do
-            REQUIRED_ITEM_INDEX=$(expr ${REQUIRED_ITEM_INDEX-0} + 1)
-            __print_required_or_optional_item $(__decode "$item")
-        done
-        unset REQUIRED_ITEM_INDEX
-    fi
-}
-
-__printf_optional_dependencies() {
-    step "list optional dependencies"
-    if [ -z "$OPTIONAL" ] ; then
-        warn "no optional dependencies."
-    else
-        printf "%-7s %-11s %-10s %-10s %s\n" TYPE NAME EXPECTED ACTUAL LOCATION
-        for item in $OPTIONAL
-        do
-            OPTIONAL_ITEM_INDEX=$(expr ${OPTIONAL_ITEM_INDEX-0} + 1)
-            __print_required_or_optional_item $(__decode "$item")
-        done
-        unset OPTIONAL_ITEM_INDEX
-    fi
 }
 
 # }}}
@@ -1539,9 +1565,8 @@ perform_config() {
             -DCMAKE_VERBOSE_MAKEFILE=ON 
             -DCMAKE_COLOR_MAKEFILE=ON 
             -Wno-dev 
-            $@
             -S . 
-            -B build.d"
+            -B build.d $@"
     fi
 
     if [ -z "$GENERATOR" ] ; then
@@ -1553,10 +1578,10 @@ perform_config() {
 
     if [ "$GENERATOR" = 'Unix Makefiles' ] ; then
         BUILD_SYS=make
-        __handle_required_item required command make
+        handle_dependency required command make
     elif [ "$GENERATOR" = 'Ninja' ] ; then
         BUILD_SYS=ninja
-        __handle_required_item required command ninja
+        handle_dependency required command ninja
     fi
 
     if run cmake $CMAKE_FLAGS ; then
@@ -1603,7 +1628,7 @@ perform_install() {
             run "$BUILD_SYS" -C "$BUILD_DIR" install
         fi
     else
-        step 'perform cmakew install'
+        [ "$DEBUG" = 'true' ] && step 'perform cmakew install'
         die "haven't configed. please run ./cmakew config first."
     fi
 }
@@ -1629,10 +1654,32 @@ perform_pack() {
 
 perform_test() {
     [ "$DEBUG" = 'true' ] && step 'perform cmakew test'
+
+    unset CTEST_FLAGS
+    unset CTEST_DIR
+    unset BUILD_DIR
+
+    for item in $@
+    do
+        case $item in
+            --test-dir) CTEST_DIR=$(getvalue "$item")
+        esac
+    done
+
     if [ -f .cmakew ] ; then
         . ./.cmakew || return 1
-        cd "$BUILD_DIR" || return 1
-        run ctest -V || return 1
+
+        if [ "$BUILD_YES" != 1 ] ; then
+            die "haven't built. please run ./cmakew build."
+        fi
+
+        if [ -z "$CTEST_DIR" ] ; then
+            CTEST_FLAGS="--test-dir $BUILD_DIR $@"
+        else
+            CTEST_FLAGS="$@"
+        fi
+
+        run ctest $CTEST_FLAGS || return 1
     else
         die "haven't configed. please run ./cmakew config first."
     fi
@@ -1678,8 +1725,8 @@ EOF
     unset STEP_NUM
     unset STEP_MESSAGE
 
-    unset REQUIRED
-    unset OPTIONAL
+    unset REQUIRED_DEPENDENCY_LIST
+    unset OPTIONAL_DEPENDENCY_LIST
 
     unset PROJECT_DIR
     unset PROJECT_NAME
@@ -1762,9 +1809,9 @@ EOF
         CMAKE_VERSION_MREQUIRED=$(grep 'CMAKE_MINIMUM_REQUIRED(VERSION\s*\[.*\])\s*$' CMakeLists.txt | sed 's/CMAKE_MINIMUM_REQUIRED(VERSION\s*\(.*\))/\1/')
     fi
     if [ -z "$CMAKE_VERSION_MREQUIRED" ] ; then
-        required command cmake
+        regist_dependency required command cmake
     else
-        required command cmake ge "$CMAKE_VERSION_MREQUIRED"
+        regist_dependency required command cmake ge "$CMAKE_VERSION_MREQUIRED"
     fi
 
     PREBUILD_BINARY_CACHED_DIR="$HOME/.cmakew"
@@ -1783,7 +1830,7 @@ EOF
             done
         fi
     fi
-    
+
     if exists command "perform_${ACTION}_pre" ; then
         eval "perform_${ACTION}_pre $@" || return 1
     fi
